/**
 * YouTube Transcript Fetcher
 * Uses YouTube's internal API to retrieve captions/transcripts.
 * No external dependencies beyond Node.js built-in fetch.
 */

const INNERTUBE_URL = 'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
const ANDROID_VERSION = '20.10.38';
const USER_AGENT = `com.google.android.youtube/${ANDROID_VERSION} (Linux; U; Android 14)`;

const INNERTUBE_CONTEXT = {
  client: {
    clientName: 'ANDROID',
    clientVersion: ANDROID_VERSION,
  }
};

/**
 * Fetch transcript for a given YouTube video ID.
 * @param {string} videoId - 11-char YouTube video ID
 * @param {string|null} preferredLang - language code (e.g., 'nl', 'en')
 * @returns {Promise<{segments: Array, language: string, isAutoGenerated: boolean}>}
 */
export async function fetchTranscript(videoId, preferredLang = null) {
  // Step 1: Get caption track list via InnerTube
  const playerResponse = await fetchPlayerData(videoId);
  const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!Array.isArray(captionTracks) || captionTracks.length === 0) {
    throw new TranscriptError('NO_TRANSCRIPT', 'Geen transcript beschikbaar voor deze video.');
  }

  // Step 2: Pick the best track
  const { track, isAutoGenerated } = selectBestTrack(captionTracks, preferredLang);

  if (!track) {
    const available = captionTracks.map(t => t.languageCode).join(', ');
    throw new TranscriptError('LANG_NOT_FOUND', `Taal niet gevonden. Beschikbare talen: ${available}`);
  }

  // Step 3: Fetch and parse the caption XML/timedtext
  const segments = await fetchCaptionSegments(track.baseUrl, track.languageCode);

  return {
    segments,
    language: track.languageCode,
    languageName: track.name?.simpleText || track.languageCode,
    isAutoGenerated,
    trackCount: captionTracks.length,
    availableLanguages: captionTracks.map(t => ({
      code: t.languageCode,
      name: t.name?.simpleText || t.languageCode,
      isAuto: t.kind === 'asr'
    }))
  };
}

async function fetchPlayerData(videoId) {
  const res = await fetch(INNERTUBE_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': USER_AGENT,
    },
    body: JSON.stringify({
      context: INNERTUBE_CONTEXT,
      videoId,
    }),
  });

  if (!res.ok) {
    throw new TranscriptError('API_ERROR', `YouTube API antwoord: ${res.status}`);
  }

  const data = await res.json();

  // Check playability
  const status = data?.playabilityStatus?.status;
  if (status === 'LOGIN_REQUIRED') throw new TranscriptError('LOGIN_REQUIRED', 'Video vereist inloggen (leeftijdsbeperking of privé).');
  if (status === 'UNPLAYABLE') throw new TranscriptError('UNAVAILABLE', 'Video niet beschikbaar.');
  if (status === 'ERROR') throw new TranscriptError('VIDEO_ERROR', 'Videofout: ' + (data?.playabilityStatus?.reason || 'onbekend'));

  return data;
}

function selectBestTrack(tracks, preferredLang) {
  // Separate manual captions from auto-generated (ASR)
  const manualTracks = tracks.filter(t => t.kind !== 'asr');
  const autoTracks = tracks.filter(t => t.kind === 'asr');

  // Try manual tracks first
  if (preferredLang) {
    const exact = manualTracks.find(t => t.languageCode === preferredLang);
    if (exact) return { track: exact, isAutoGenerated: false };

    // Partial match (e.g., 'en' matches 'en-US')
    const partial = manualTracks.find(t => t.languageCode.startsWith(preferredLang));
    if (partial) return { track: partial, isAutoGenerated: false };

    // Try auto-generated in preferred lang
    const autoExact = autoTracks.find(t => t.languageCode === preferredLang);
    if (autoExact) return { track: autoExact, isAutoGenerated: true };

    const autoPartial = autoTracks.find(t => t.languageCode.startsWith(preferredLang));
    if (autoPartial) return { track: autoPartial, isAutoGenerated: true };
  }

  // No preference: take first manual, then first auto
  if (manualTracks.length > 0) return { track: manualTracks[0], isAutoGenerated: false };
  if (autoTracks.length > 0) return { track: autoTracks[0], isAutoGenerated: true };
  
  return { track: tracks[0], isAutoGenerated: false };
}

async function fetchCaptionSegments(baseUrl, langCode) {
  // Request JSON format from YouTube's timedtext API
  const url = new URL(baseUrl);
  url.searchParams.set('fmt', 'json3');

  const res = await fetch(url.toString(), {
    headers: {
      'User-Agent': USER_AGENT,
      'Accept-Language': langCode,
    }
  });

  if (!res.ok) {
    throw new TranscriptError('CAPTION_FETCH_ERROR', `Kan ondertitels niet laden: ${res.status}`);
  }

  const contentType = res.headers.get('content-type') || '';

  if (contentType.includes('json')) {
    return parseJson3Format(await res.json());
  } else {
    // Fallback: XML timedtext format
    return parseXmlFormat(await res.text());
  }
}

function parseJson3Format(data) {
  const events = data?.events || [];
  const segments = [];

  for (const event of events) {
    if (!event.segs) continue;
    const offsetMs = event.tStartMs || 0;
    const durationMs = event.dDurationMs || 0;

    const text = event.segs
      .map(s => s.utf8 || '')
      .join('')
      .replace(/\n/g, ' ')
      .trim();

    if (!text || text === '\n') continue;

    segments.push({
      text: decodeHtmlEntities(text),
      start: offsetMs,
      duration: durationMs,
    });
  }

  return segments;
}

function parseXmlFormat(xml) {
  const segments = [];

  // Match <text start="..." dur="...">content</text>
  const textRegex = /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let match;

  while ((match = textRegex.exec(xml)) !== null) {
    const startSec = parseFloat(match[1]);
    const durSec = parseFloat(match[2]);
    const rawText = match[3].replace(/<[^>]+>/g, '').replace(/\n/g, ' ').trim();
    const text = decodeHtmlEntities(rawText);

    if (text) {
      segments.push({
        text,
        start: Math.round(startSec * 1000),
        duration: Math.round(durSec * 1000),
      });
    }
  }

  return segments;
}

function decodeHtmlEntities(str) {
  return str
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)));
}

export class TranscriptError extends Error {
  constructor(code, message) {
    super(message);
    this.code = code;
    this.name = 'TranscriptError';
  }
}
