import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { fetchTranscript, TranscriptError } from './transcript.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3003;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../frontend')));

// Extract video ID from various YouTube URL formats
function extractVideoId(url) {
  if (!url) return null;
  
  const patterns = [
    /youtu\.be\/([a-zA-Z0-9_-]{11})/,
    /[?&]v=([a-zA-Z0-9_-]{11})/,
    /\/embed\/([a-zA-Z0-9_-]{11})/,
    /\/shorts\/([a-zA-Z0-9_-]{11})/,
    /\/live\/([a-zA-Z0-9_-]{11})/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }

  // Bare 11-char ID
  if (/^[a-zA-Z0-9_-]{11}$/.test(url.trim())) return url.trim();
  
  return null;
}

// Format milliseconds → MM:SS or HH:MM:SS
function formatTimestamp(ms) {
  const totalSeconds = Math.floor((ms || 0) / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  
  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  }
  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

// Classify a transcript segment
function classifySegment(text, isAutoGenerated) {
  const trimmed = text.trim();
  
  // Annotations: text in brackets/parentheses, music symbols
  if (
    (trimmed.startsWith('[') && trimmed.endsWith(']')) ||
    (trimmed.startsWith('(') && trimmed.endsWith(')')) ||
    (trimmed.startsWith('（') && trimmed.endsWith('）')) ||
    /♪|♫|🎵|🎶/.test(trimmed)
  ) {
    return 'annotation';
  }

  return isAutoGenerated ? 'auto' : 'transcript';
}

app.get('/api/transcript', async (req, res) => {
  const { url, lang } = req.query;
  
  if (!url) {
    return res.status(400).json({ 
      error: 'Geen URL opgegeven',
      message: 'Geef een YouTube URL mee als parameter ?url='
    });
  }
  
  const videoId = extractVideoId(url);
  
  if (!videoId) {
    return res.status(400).json({ 
      error: 'Ongeldige URL',
      message: 'Kan geen geldig video-ID vinden. Probeer een link zoals https://www.youtube.com/watch?v=... of https://youtu.be/...'
    });
  }
  
  try {
    const result = await fetchTranscript(videoId, lang || null);

    const segments = result.segments.map((item, index) => {
      const type = classifySegment(item.text, result.isAutoGenerated);
      return {
        index,
        text: item.text,
        start: item.start,
        duration: item.duration,
        timestamp: formatTimestamp(item.start),
        type
      };
    });

    const fullText = segments
      .map(s => `[${s.timestamp}] ${s.text}`)
      .join('\n');

    const plainText = segments
      .filter(s => s.type !== 'annotation')
      .map(s => s.text)
      .join(' ');

    const stats = {
      total: segments.length,
      transcript: segments.filter(s => s.type === 'transcript').length,
      auto: segments.filter(s => s.type === 'auto').length,
      annotation: segments.filter(s => s.type === 'annotation').length,
    };

    res.json({
      videoId,
      url: `https://www.youtube.com/watch?v=${videoId}`,
      language: result.language,
      languageName: result.languageName,
      isAutoGenerated: result.isAutoGenerated,
      availableLanguages: result.availableLanguages,
      segments,
      fullText,
      plainText,
      stats
    });

  } catch (error) {
    console.error('Transcript error:', error.code, error.message);

    if (error instanceof TranscriptError) {
      const statusMap = {
        NO_TRANSCRIPT: [404, 'Geen transcript'],
        LANG_NOT_FOUND: [404, 'Taal niet beschikbaar'],
        LOGIN_REQUIRED: [403, 'Inloggen vereist'],
        UNAVAILABLE: [404, 'Video niet beschikbaar'],
        VIDEO_ERROR: [400, 'Videofout'],
        API_ERROR: [502, 'YouTube API fout'],
        CAPTION_FETCH_ERROR: [502, 'Ondertitel fout'],
      };

      const [status, title] = statusMap[error.code] || [500, 'Fout'];
      return res.status(status).json({ error: title, message: error.message });
    }

    res.status(500).json({
      error: 'Serverfout',
      message: `Onverwachte fout: ${error.message}`
    });
  }
});

// Available languages for a video
app.get('/api/languages', async (req, res) => {
  const { url } = req.query;
  const videoId = extractVideoId(url || '');
  if (!videoId) return res.status(400).json({ error: 'Ongeldige URL' });

  try {
    const result = await fetchTranscript(videoId, null);
    res.json({ availableLanguages: result.availableLanguages });
  } catch (e) {
    res.status(404).json({ error: e.message });
  }
});

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../frontend', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`✅ YouTube Transcript Tool draait op http://localhost:${PORT}`);
});
